export type SuperCategory = "school_tutoring" | "higher_education" | "professional_skills";

export const SCHOOL_TUTORING_SUBJECTS = [
  "Mathematics",
  "English",
  "Kiswahili",
  "Physics",
  "Chemistry",
  "Biology",
  "History",
  "Geography",
  "Computer Studies",
  "Business Studies",
  "Agriculture",
  "Home Science",
  "Art & Design",
  "Music",
  "French",
  "German",
  "Arabic",
  "Religious Education (CRE)",
  "Religious Education (IRE)",
  "Social Studies",
  "Science & Technology",
  "Creative Arts",
  "Life Skills",
] as const;

export const HIGHER_EDUCATION_SUBJECTS = [
  "Accounting & Finance",
  "Actuarial Science",
  "Architecture",
  "Biochemistry",
  "Biomedical Engineering",
  "Business Administration",
  "Civil Engineering",
  "Clinical Medicine",
  "Communication & Media",
  "Computer Science",
  "Data Science & Analytics",
  "Dentistry",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Environmental Science",
  "Food Science & Nutrition",
  "Geology",
  "Health Sciences",
  "Hospitality & Tourism",
  "Human Resource Management",
  "Information Technology",
  "International Relations",
  "Journalism",
  "Law",
  "Library & Information Science",
  "Marketing",
  "Mathematics & Statistics",
  "Mechanical Engineering",
  "Medicine & Surgery",
  "Microbiology",
  "Nursing",
  "Pharmacy",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Sociology",
  "Software Engineering",
  "Supply Chain Management",
  "Veterinary Medicine",
] as const;

export const CATEGORY_LABELS: Record<SuperCategory, string> = {
  school_tutoring: "School Tutoring",
  higher_education: "Higher Education",
  professional_skills: "Professional Skills",
};

export const CATEGORY_DESCRIPTIONS: Record<SuperCategory, string> = {
  school_tutoring: "Primary & secondary school subjects (CBC, KCPE, KCSE)",
  higher_education: "University and college-level subjects",
  professional_skills: "Business, tech, and career skills (type your own)",
};
